sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: rZXKckiErW6FCKVUxTtxcumKaA6OajVN55SO+NZoP5o+UwGI7S3GeUIgOEEdjSLOoLPQkUmtPKM/82pDffydDpia/JzwHxu5rfU3WLLtW5LMdXVGX68Venyy6mJuldn36r0Hyq2EaCEbJ9FbPMJfn9SRRrNFMtNXjuizL1+qIwdEOkF5dp89TXQFL5b9prKfESFSjpcmrhXEBsQAVcM1XMQZIAkZcBLE7a0BMabt52EKgpVLucwQCnIU9MDLhKyDjvR+KuPdczGABXAQ2OhewtUyi1i3M8o3pHwLgJKbciqMHwkQpQjIRgFJbtx5ozyL+sfLjctDUPwYd3XKeIFZ878yvUg3QXZ+VY0bnAnBGkLH9rdyL7bAgVu+n1Hi5cuqDAf9EfGutgte6IrtKN3T8fSdWvqQ2ZKSFmHOMCLMkawMDBeEKV3lg7dOzilRrF/uwxTc8xTih0klCGvox5bjDVS2sjbeh8sJFH3NwA8zX69cbsWmDBvNMTb3qXswH6kslvqjWRhaybephdwWvVtmbIVQzMdITwDeZBJv1awpPmmTddmaX6GJxf1hvLt2MUresIHg+ZEa0xtvtU3fYhCUTGAc6tfIHnuNnsfRk3ZrA+09feeBeUZjGkeZlG15ERrfoWPeHXBQ/HdR5/8Rbj6MKJyVlJrq0MDTqI5R7GrA1to=
    - secure: 6KM6yjw2Q41USUX8TY5KFjVga2HFEf/db3qvSbfpHM5IJy1R4CikOBTSQEb0AYp0+7ASpN/QdeizK6DfF+EDXfkXtQHn6u1Oq9HS3QjM2wQcBwVzrxTPtuP78XJRrlEkyKIgURVRCzPp3BGW6UQEuAFyf1G+WMH0lzqpxmabnNPNW3SNBpaKsVe9L1v4qvEBvJjI+wGavHE/WMC3Ffn/6LmgoJiRhU8Cs42IKlI9OPBdeq9SZ1vqjc1kn5w8qJJNO+w38nbMyfRkQtKCqZLLSfEsQys2NfSicK5YBM6k+rN3coi+CsaAeJzTVgM0X3ZxQzufCwFcXF/iZ50+PgnAwxKWYowG8SPwqpkvyz5+a7FYlCK+kvrvtNx8TDNvI3rnCYDMGhtry77BWGlO8C2iZCd4s7KJl4v2nffpwZ2GxSIQmsas8kOx18/+IzdpZb0U9vsTbN49kUqRDDDM8s7NB2CJTuU1Ib354yP/kYXLHlmc14N8zPjZVzEiJRSJMrkmBLFzV4GRXVwAJ2JwEnRFkmUtszWTtIJUM46DQtkmI9cYYnItbL+Rcq8rJ+w6qRymGwE9LgtdgyeHv4OVeA2zHFsKKuxTx5w+CVtDuz+NTwhenjun8zxpoMP9UY+4MAZzes9R79+myHpx8TZIug9RzTeg/Xpau84hxG4g8avpAJQ=
